version: '3.4'

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD:
  MYSQL_DATABASE: proxy
  REACT_APP_SERVER_PORT: 80

services:
  web:
    build: .
    ports:
      - "80:80"
  db:
    image: "mysql"
    environment:
      <<:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db-data:/proxy-db

volumes:
  db-data: